
###
GET http://localhost:3070/api/v1/users

###
PATCH http://localhost:3070/api/v1/users
Content-Type: application/json
some-other-header: with my very personal information

{
    "id": "johndoe0",
    "email": "this is a patch"
}